### ISSUE TITLE
[ISSUE 제안] [11/28 ~ 12/02] TODO

### ISSUE THREAD

**Issue by haedal-uni** [Lluora/DangDang#12]
* 아래와 같이 TODO 리스트를 적어서 ISSUE에 올리는 것은 어떤가요??

작업 상세 내용

- [x] dropdown 버튼 

- [x] 주소 검색 버튼

- [x] 게시글 작성 란

- [x] 게시글 등록 버튼

- [x] 주소 검색 시 게시글 작성 란 hide

**Comment by haedal-uni** [comment]
#### 현재까지 구현한 웹페이지
<img src = https://user-images.githubusercontent.com/74857364/143730380-d9dd4059-60c0-41fd-ae5f-fccb5c5fef12.png width="50%">


- dropdown 리스트 중 원하는 옵션 클릭 시 클릭한 옵션으로 전환
- 기존 css 스크롤바 : hidden으로 변경 (detail.css)
- 글 작성 란 : textarea 테두리 제거 및 placeholder로 작성하는 공간 명시함 
   (박스 크기 이상으로 글 작성 시 스크롤바 자동생성)

**Comment by great-psycho** [comment]
현재 진행 상황을 체크 박스로 표현하는게 깔끔하고 좋은 거 같습니다!
