### ISSUE TITLE
[11/29~12/03] TODO

### ISSUE THREAD

**Issue by great-psycho** [Lluora/DangDang#19]
- [x] API설계
- [x] 사진 가져오기 구현 (GET)
- [ ] 프로필 가져오기 (GET)
- [x] 글 내용 가져오기 (GET)
- [ ] 프로필 가져오기 (GET)
- [ ] 강아지 크기별 분류
- [ ] 사진 업로드 무한 스크롤 구현
